var GAME_LEVELS = [
   ["                                                                                ",
   "                             !!!                                                ",
   "                            !!!!!                                               ",
   "                           !!!!!!!                                              ",
   "                            v  v                                   x            ",
   "                                                                =               ",
   "                                              x     x     xx     x   x          ",
   "                                          x                      x!!vx          ",
   "                         x            x                          xv! x          ",
   "                          x     x                                x v x          ",
   "   ^                      x                                                 xx  ",
   "  xx          =           x                                                  x  ",
   "  x                      x   x                                               x  ",
   "  x     xx     =         x       xx      ^                                 > x  ",
   "  x          xxxx   xx                xxxxxxxx  xxxxxxxx                     x  ",
   "  x  @     = x                                                               x  ",
   "  xxxxxxxxxxxx !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx  ",
   "                                                                                "],
  
    
  ["                                              x                                               x               ",
   "                                              x                                               x               ",
   "                       x      x       x       x                                               x               ",
   "                       x     =x=      x      =x                                v              x               ",
   "                      xxxxxxxxxxxxxxxxx       x      xxxx     x                               x               ",
   "                       x              xx     =x         x     x                               x               ",
   "                       x              x       x         x=    x                               x               ",
   "                       x              x                 x     x                      xxxxx    x               ",
   "                      x               x          x      xx    x                         =x=   x               ",
   "                                      xx=               x     x                          x    x               ",
   "                                      x                 x    xx                          x    x               ",
   "                                      x                xx    =x                  x       x =  x               ",
   "                     xx               x                 x     x=                         x    x               ",
   "                                      xxxxxxx    xx     xx    x            x             x    x               ",
   "                          x                             x     x                          x    x               ",
   "                         x                    xxxxxxxxxxx=    x                          x    x               ",
   "          xxxxxx        x                               x    xx                  x       x  = x               ",
   "          xvxxvx       x                                x                                x    x               ",
   "                                                        x                   x            x    x               ",
   "                                                        x                                x >  x               ",
   "                                                        x                                xxxxxx               ",
   "                     xx                                 xxxxxxxxxxxxxxxxxx                                    ",
   "            xx       =x                                                                                       ",
   "      @         x                                                         xxxxxxxxxxxxxxx                     ",
   "     xxx                                                                                                      ",
   "                                                                                                              ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "],
    
    
    
    
    
    
    
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                                                                                             ",
   "x                                                                                                             ",
   "x                                                                                                             ",
   "x                    x   x                                                                                    ",
   "x=                  x     x                                                                                   ",
   "x                   x     x                              x        x                                           ",
   "x                   x     x                        xx                                                         ",
   "x                  x     v x                                  x                                               ",
   "x       =          xxx     x               xxxxx                       xx                                     ",
   "x                  xv      x                                           x                                      ",
   "x                 xx       x                                           x                                      ",
   "x                  x       x                 =                  =      x                                      ",
   "x                  x       x                       x                   x           xxxxxxxxx                  ",
   "x                  x       x                             x            =x          x         x                 ",
   "x         =       x      xxx                                  x       xx         x           x                ",
   "x                 x      v  x                                         x         x             x               ",
   "x                 x         x                                         x        x               x              ",
   "x                xx         x                  !!!!!!!!!!!!!!!        x       x                 x             ",
   "x                 x         x                 !xxxxxxxxxxxxxxxx      xx      x                                ",
   "x                 x         x              !!!x                       x       x      >                        ",
   "x    =            x         x             !xxx                        x        x    xxxxx                     ",
   "x                xxxx       =x        !!!!x vv                        x         x         x                   ",
   "x                x           x       !xxxx                           x           x            x               ",
   "x                x    !!xxxxxx!!!!!!!x               x        x                   x          x x        x     ",
   "x               xx    xx v   vxxxxxxx                                              x!!!!!!!!x  x!       x     ",
   "x                x                              x        x      =x                  xxxxxxxx   x!       x     ",
   "x=               x                         x                                                   x! x     x     ",
   "x         =      x                                                                             x  v     x     ",
   "x            xxxxxxxxxxxxxxxxxxxxxxxxxxx                                                       x        x     ",
   "x           x                             xxxxxxxxxxxxxx                                       x        x     ",
   "x          x                                                                                   x       xx     ",
   "x   @     x                                                                                    x        x     ",
   "xxxxx                                                                                          x    x   x     ",
   "                                                                                               x    v   x     ",
   "                                                                                               x        x     ",
   "                                                                                               xx       x     ",
   "                                                                                               x        x     ",
   "                                                                                               x        x     ",
   "                                                                                               x        x     ",
   "                                                                                               xxxxxxxxxx     ",
   "                                                                                                              ",]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
